name: Build & Deploy (GitHub Pages + Cordova)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cordova CLI
        run: npm i -g cordova@13

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-36" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Create Cordova project
        run: |
          cordova create cordova com.easierbycode.game2019es7 "2019-es7"
          cd cordova
          cordova telemetry off
          cordova platform add android@14.0.1

      - name: Update config.xml for Android 16 beta
        run: |
          # Set target-sdk to 36 (Android 16)
          if grep -q "android-targetSdkVersion" cordova/config.xml; then
            sed -i 's/android-targetSdkVersion" value="[0-9]*"/android-targetSdkVersion" value="36"/' cordova/config.xml
          else
            sed -i '/<\/widget>/i \    <preference name="android-targetSdkVersion" value="36" \/>' cordova/config.xml
          fi

      - name: Ensure cordova vibration plugin is installed
        working-directory: cordova
        run: |
          cordova plugin add cordova-plugin-vibration || true

      - name: Prepare Cordova www
        run: |
          rm -rf cordova/www/*
          cp -r assets cordova/www/
          cp -r src cordova/www/
          cp index.html cordova/www/
          cp favicon.ico cordova/www/ || true
          cp app-original.js cordova/www/ || true
          # Inject cordova.js into index.html
          sed -i 's/<\/head>/<script src="cordova.js"><\/script><\/head>/' cordova/www/index.html

      - name: Build Cordova Android (APK)
        working-directory: cordova
        run: cordova build android --debug --packageType=apk

      - name: Prepare Web Deployment
        run: |
          mkdir dist
          cp -r assets dist/
          cp -r src dist/
          cp index.html dist/
          cp favicon.ico dist/ || true
          cp app-original.js dist/ || true
          # Find the built APK and copy it to dist/game.apk
          find cordova/platforms/android/app/build/outputs/apk/debug -name "*.apk" -exec cp {} dist/game.apk \;

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

