#!/bin/bash
# build.sh — Build script for PS2 AthenaEnv port
# Prepares assets and creates a deployable PS2 package
#
# Prerequisites:
#   - AthenaEnv v4 SDK installed
#   - ffmpeg (for audio conversion)
#   - ImageMagick or similar (for atlas conversion)
#   - mkisofs or genisoimage (for ISO creation)
#
# Usage:
#   cd src/ps2/deploy
#   ./build.sh [--iso]
#
# Output:
#   build/         — Ready-to-run directory for PS2
#   build.iso      — PS2 bootable ISO (if --iso flag passed)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
PS2_SRC="$PROJECT_ROOT/src/ps2"
WEB_ASSETS="$PROJECT_ROOT/assets"
BUILD_DIR="$SCRIPT_DIR/build"
BUILD_ISO=false

if [ "$1" = "--iso" ]; then
    BUILD_ISO=true
fi

echo "=== PS2 AthenaEnv Build ==="
echo "Project root: $PROJECT_ROOT"
echo "Build dir: $BUILD_DIR"

# Clean build directory
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/assets/sounds"
mkdir -p "$BUILD_DIR/assets/sounds/scene_continue"
mkdir -p "$BUILD_DIR/assets/sounds/scene_game"
mkdir -p "$BUILD_DIR/assets/img/stage"
mkdir -p "$BUILD_DIR/src/ps2"

# --- Step 1: Bundle JS files ---
echo "[1/5] Bundling JavaScript..."

JS_FILES=(
    "constants.js"
    "game_state.js"
    "atlas.js"
    "draw.js"
    "sprite.js"
    "tween.js"
    "timer.js"
    "sound.js"
    "input.js"
    "hud.js"
    "projectile.js"
    "player.js"
    "enemy.js"
    "boss.js"
    "scenes.js"
    "scene_title.js"
    "scene_adv.js"
    "scene_game.js"
    "scene_continue.js"
    "scene_ending.js"
)

# Create bundled main.js (all modules concatenated)
BUNDLE="$BUILD_DIR/main.js"
echo "// PS2 STG - AthenaEnv Port (bundled)" > "$BUNDLE"
echo "// Auto-generated by build.sh" >> "$BUNDLE"
echo "" >> "$BUNDLE"

for f in "${JS_FILES[@]}"; do
    echo "// === $f ===" >> "$BUNDLE"
    cat "$PS2_SRC/$f" >> "$BUNDLE"
    echo "" >> "$BUNDLE"
done

# Append the main loop (without the module loading section)
echo "// === main entry ===" >> "$BUNDLE"
# Extract main.js content after the module loading IIFE
sed -n '/^\/\/ --- Asset Loading ---$/,$p' "$PS2_SRC/main.js" >> "$BUNDLE"

echo "  Bundled $(wc -l < "$BUNDLE") lines"

# --- Step 2: Copy/convert texture atlases ---
echo "[2/5] Processing texture atlases..."

# Copy atlas JSON files
if [ -f "$WEB_ASSETS/game_ui.json" ]; then
    cp "$WEB_ASSETS/game_ui.json" "$BUILD_DIR/assets/game_ui.json"
    echo "  Copied game_ui.json"
fi

if [ -f "$WEB_ASSETS/game_asset.json" ]; then
    cp "$WEB_ASSETS/game_asset.json" "$BUILD_DIR/assets/game_asset.json"
    echo "  Copied game_asset.json"
fi

# Copy atlas PNG images (or convert if they're in another format)
for atlas in game_ui game_asset; do
    if [ -f "$WEB_ASSETS/${atlas}.png" ]; then
        cp "$WEB_ASSETS/${atlas}.png" "$BUILD_DIR/assets/${atlas}.png"
        echo "  Copied ${atlas}.png"
    elif [ -f "$WEB_ASSETS/${atlas}.jpg" ]; then
        if command -v convert &>/dev/null; then
            convert "$WEB_ASSETS/${atlas}.jpg" "$BUILD_DIR/assets/${atlas}.png"
            echo "  Converted ${atlas}.jpg -> png"
        else
            cp "$WEB_ASSETS/${atlas}.jpg" "$BUILD_DIR/assets/${atlas}.png"
            echo "  Copied ${atlas}.jpg (needs manual conversion)"
        fi
    fi
done

# Copy game recipe
if [ -f "$WEB_ASSETS/game.json" ]; then
    cp "$WEB_ASSETS/game.json" "$BUILD_DIR/assets/game.json"
    echo "  Copied game.json"
fi

# --- Step 3: Convert audio ---
echo "[3/5] Converting audio files..."

convert_audio() {
    local src="$1"
    local dst="$2"
    local fmt="$3"

    if [ ! -f "$src" ]; then
        echo "  SKIP: $src (not found)"
        return
    fi

    if command -v ffmpeg &>/dev/null; then
        if [ "$fmt" = "wav" ]; then
            ffmpeg -y -i "$src" -acodec pcm_s16le -ar 22050 -ac 1 "$dst" 2>/dev/null
        elif [ "$fmt" = "ogg" ]; then
            ffmpeg -y -i "$src" -acodec libvorbis -ar 44100 -ac 2 -q:a 4 "$dst" 2>/dev/null
        fi
        echo "  Converted: $(basename "$dst")"
    else
        echo "  SKIP: ffmpeg not found, cannot convert $(basename "$src")"
    fi
}

# Convert SFX to WAV (22kHz mono for PS2 memory)
SFX_LIST=(
    "se_shoot" "se_shoot_b" "se_explosion" "se_damage" "se_guard"
    "se_sp" "se_sp_explosion" "se_barrier_start" "se_barrier_end"
    "se_decision" "se_correct" "se_cursor" "se_over"
    "se_finish_akebono"
)
for sfx in "${SFX_LIST[@]}"; do
    convert_audio "$WEB_ASSETS/sounds/${sfx}.mp3" "$BUILD_DIR/assets/sounds/${sfx}.wav" "wav"
done

# Convert voice clips to WAV
VOICE_LIST=(
    "voice_titlecall" "voice_fight" "voice_ko" "voice_another_fighter"
    "voice_congra" "voice_gameover" "voice_thankyou"
    "voice_round0" "voice_round1" "voice_round2" "voice_round3"
    "g_damage_voice" "g_powerup_voice" "g_sp_voice"
    "g_adbenture_voice0"
)
for v in "${VOICE_LIST[@]}"; do
    src_path="$WEB_ASSETS/sounds/${v}.mp3"
    if [ ! -f "$src_path" ]; then
        # Try subdirectory patterns
        for subdir in scene_title scene_adventure scene_game scene_clear ui; do
            if [ -f "$WEB_ASSETS/sounds/${subdir}/${v}.mp3" ]; then
                src_path="$WEB_ASSETS/sounds/${subdir}/${v}.mp3"
                break
            fi
        done
    fi
    convert_audio "$src_path" "$BUILD_DIR/assets/sounds/${v}.wav" "wav"
done

# Continue scene voices
for i in $(seq 0 9); do
    convert_audio "$WEB_ASSETS/sounds/scene_continue/voice_countdown${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_continue/voice_countdown${i}.wav" "wav"
done
for i in 0 1 2; do
    convert_audio "$WEB_ASSETS/sounds/scene_continue/g_continue_yes_voice${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_continue/g_continue_yes_voice${i}.wav" "wav"
done
for i in 0 1; do
    convert_audio "$WEB_ASSETS/sounds/scene_continue/g_continue_no_voice${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_continue/g_continue_no_voice${i}.wav" "wav"
done

# Stage voices
for i in $(seq 0 4); do
    convert_audio "$WEB_ASSETS/sounds/scene_game/g_stage_voice_${i}.mp3" \
        "$BUILD_DIR/assets/sounds/scene_game/g_stage_voice_${i}.wav" "wav"
done

# Boss voices and BGM
BOSS_NAMES=("bison" "barlog" "sagat" "vega" "goki" "fang")
for bn in "${BOSS_NAMES[@]}"; do
    convert_audio "$WEB_ASSETS/sounds/boss_${bn}_voice_add.mp3" \
        "$BUILD_DIR/assets/sounds/boss_${bn}_voice_add.wav" "wav"
    convert_audio "$WEB_ASSETS/sounds/boss_${bn}_voice_ko.mp3" \
        "$BUILD_DIR/assets/sounds/boss_${bn}_voice_ko.wav" "wav"
    convert_audio "$WEB_ASSETS/sounds/boss_${bn}_bgm.mp3" \
        "$BUILD_DIR/assets/sounds/boss_${bn}_bgm.ogg" "ogg"
done

# Other BGM
convert_audio "$WEB_ASSETS/sounds/scene_adventure/adventure_bgm.mp3" \
    "$BUILD_DIR/assets/sounds/adventure_bgm.ogg" "ogg"
convert_audio "$WEB_ASSETS/sounds/scene_continue/bgm_continue.mp3" \
    "$BUILD_DIR/assets/sounds/bgm_continue.ogg" "ogg"
convert_audio "$WEB_ASSETS/sounds/scene_continue/bgm_gameover.mp3" \
    "$BUILD_DIR/assets/sounds/bgm_gameover.ogg" "ogg"

# --- Step 4: Copy stage backgrounds ---
echo "[4/5] Copying stage backgrounds..."

for i in $(seq 0 4); do
    for type in loop end; do
        if [ -f "$WEB_ASSETS/img/stage/stage_${type}${i}.png" ]; then
            cp "$WEB_ASSETS/img/stage/stage_${type}${i}.png" "$BUILD_DIR/assets/img/stage/"
            echo "  Copied stage_${type}${i}.png"
        fi
    done
done

if [ -f "$WEB_ASSETS/img/title_bg.jpg" ]; then
    if command -v convert &>/dev/null; then
        convert "$WEB_ASSETS/img/title_bg.jpg" "$BUILD_DIR/assets/img/title_bg.png"
    else
        cp "$WEB_ASSETS/img/title_bg.jpg" "$BUILD_DIR/assets/img/title_bg.jpg"
    fi
fi

# --- Step 5: Create AthenaEnv boot config ---
echo "[5/5] Creating boot configuration..."

cat > "$BUILD_DIR/system.cnf" << 'EOF'
BOOT2 = cdrom0:\MAIN.JS;1
VER = 1.00
VMODE = NTSC
EOF

cat > "$BUILD_DIR/README.txt" << 'EOF'
PS2 STG - AthenaEnv Port
========================

A port of the Capcom April Fool 2019 STG game to PlayStation 2
using the AthenaEnv v4 JavaScript runtime.

Requirements:
- PlayStation 2 console (or PCSX2 emulator)
- AthenaEnv v4 runtime installed on memory card

Controls:
- D-pad / Left Stick: Move player
- Cross (X): Confirm / Start game
- Circle: Back
- Triangle / R1: SP attack (when gauge is full)
- Start: Pause / Start

Installation:
1. Copy the entire build directory to your PS2 memory card
2. Launch AthenaEnv and select main.js
3. Or burn to DVD as a bootable ISO

Original game (C) CAPCOM
Port engine: AthenaEnv v4
EOF

# --- Optional: Create ISO ---
if [ "$BUILD_ISO" = true ]; then
    echo "Creating ISO image..."
    if command -v mkisofs &>/dev/null; then
        mkisofs -o "$SCRIPT_DIR/ps2_stg.iso" \
            -V "PS2STG" \
            -sysid "PLAYSTATION" \
            -publisher "HOMEBREW" \
            -no-emul-boot \
            "$BUILD_DIR"
        echo "ISO created: $SCRIPT_DIR/ps2_stg.iso"
    elif command -v genisoimage &>/dev/null; then
        genisoimage -o "$SCRIPT_DIR/ps2_stg.iso" \
            -V "PS2STG" \
            -sysid "PLAYSTATION" \
            "$BUILD_DIR"
        echo "ISO created: $SCRIPT_DIR/ps2_stg.iso"
    else
        echo "WARNING: mkisofs/genisoimage not found, skipping ISO creation"
    fi
fi

echo ""
echo "=== Build Complete ==="
echo "Output: $BUILD_DIR/"
echo "Files: $(find "$BUILD_DIR" -type f | wc -l)"
echo ""
echo "To test on PCSX2:"
echo "  1. Install AthenaEnv v4 ELF on virtual memory card"
echo "  2. Point AthenaEnv to: $BUILD_DIR/main.js"
