// Builds the importable characters module. Run from the repo root:
//
//   node characters/build.mjs
//
// Outputs (committed, served by GitHub Pages under /2019-es7/characters/):
//   characters/index.js    bare `svelte`/`phaser` externals — for bundlers,
//                          Deno, and import-map pages
//   characters/browser.js  same module with svelte pinned to the esm.sh build
//                          used by cmg's scene-script runtime — importable
//                          directly in any browser page
//   characters/editor.js   self-contained <character-editor> custom element
//   characters/demo.js     compiled demo (see demo.html)
//
// Also regenerates src/generated.js (one named export per character in the
// library); when the database is unreachable the committed file is kept.

import { build, transform } from "esbuild";
import sveltePlugin from "esbuild-svelte";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = (f) => join(here, "src", f);
const out = (f) => join(here, f);

const DB = process.env.CHARACTERS_DB || "https://evil-invaders-default-rtdb.firebaseio.com";
// Must match SCENE_SCRIPT_DEFAULTS.svelteCdn in cmg's scene-script.js so the
// module and in-browser-compiled scene scripts share one svelte runtime.
const SVELTE_CDN = "https://esm.sh/svelte@5.16.0";

const RESERVED = new Set([
  "default", "class", "function", "var", "let", "const", "new", "delete",
  "import", "export", "in", "of", "if", "else", "return",
  // names the module already exports (index.js re-exports + its own API)
  "character", "Character", "Adopt", "CHARACTERS",
  "Game", "Scene", "Spawner", "Sprite", "Text", "TileSprite", "Rectangle",
  "Container", "ArcadePhysics", "ArcadeCollider",
]);

// Svelte templates parse lowercase tags as HTML elements, so each character
// also gets a PascalCase alias usable directly as <RedDressKiller/>.
function pascal(name) {
  const p = name.replace(/[_-]+(.)/g, (_m, c) => c.toUpperCase());
  return p.charAt(0).toUpperCase() + p.slice(1);
}

async function regenerateNamedExports() {
  let names;
  try {
    const res = await fetch(`${DB}/characters.json?shallow=true`, {
      signal: AbortSignal.timeout(15000),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const keys = await res.json();
    names = keys ? Object.keys(keys).sort() : [];
  } catch (e) {
    console.warn(`! could not list /characters (${e.message}) — keeping committed generated.js`);
    return;
  }
  const exportable = [];
  const skipped = [];
  for (const n of names) {
    if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) && !RESERVED.has(n)) exportable.push(n);
    else skipped.push(n);
  }
  const seen = new Set(RESERVED);
  const exportLines = [];
  for (const n of exportable) {
    exportLines.push(`export const ${n} = character(${JSON.stringify(n)});`);
    seen.add(n);
    const alias = pascal(n);
    if (alias !== n && /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(alias) && !seen.has(alias)) {
      exportLines.push(`export { ${n} as ${alias} };`);
      seen.add(alias);
    }
  }
  const lines = [
    "// GENERATED by characters/build.mjs — one export per /characters entry",
    "// (plus a PascalCase alias, since Svelte templates need capitalized tags).",
    "// Characters added after this build still work via character('<name>').",
    'import { character } from "./factory.js";',
    "",
    ...exportLines,
    "",
    `export const CHARACTERS = ${JSON.stringify(names, null, 2)};`,
    "",
  ];
  if (skipped.length) {
    lines.splice(2, 0, `// Not valid identifiers, use character(name): ${skipped.join(", ")}`);
  }
  writeFileSync(src("generated.js"), lines.join("\n"));
  console.log(`✓ generated.js — ${exportable.length} named exports${skipped.length ? `, ${skipped.length} skipped` : ""}`);
}

// 5velte-ph4ser's .svelte files use lang="ts"; strip types with esbuild.
const typescriptScripts = {
  script: async ({ content, attributes }) => {
    if (attributes.lang !== "ts") return;
    const { code } = await transform(content, { loader: "ts" });
    return { code };
  },
};

function svelte(extra = {}) {
  return sveltePlugin({
    preprocess: [typescriptScripts],
    compilerOptions: { css: "injected", ...extra },
  });
}

function pinSvelteToCdn(code) {
  // Same rewrite cmg's scene-script.js applies to compiled scene scripts.
  return code.replace(
    /((?:from|import)\s*\(?\s*)(["'])(svelte(?:\/[^"']*)?)\2/g,
    (_m, pre, q, spec) => pre + q + SVELTE_CDN + spec.slice("svelte".length) + q,
  );
}

async function bundle(entry, options = {}) {
  const result = await build({
    entryPoints: [src(entry)],
    bundle: true,
    format: "esm",
    write: false,
    conditions: ["svelte", "browser"],
    logLevel: "warning",
    ...options,
  });
  return result.outputFiles[0].text;
}

await regenerateNamedExports();

const banner =
  "// GENERATED by characters/build.mjs — edit characters/src/* and rebuild.\n";

const index = banner + (await bundle("index.js", {
  external: ["svelte", "svelte/*", "phaser"],
  plugins: [svelte()],
}));
writeFileSync(out("index.js"), index);
console.log("✓ index.js");

writeFileSync(out("browser.js"), pinSvelteToCdn(index));
console.log("✓ browser.js");

const editor = banner + (await bundle("editor/editor-entry.js", {
  plugins: [svelte({ customElement: true })],
  minify: true,
}));
writeFileSync(out("editor.js"), editor);
console.log("✓ editor.js");

const demo = banner + pinSvelteToCdn(await bundle("demo-entry.js", {
  external: ["svelte", "svelte/*", "./browser.js"],
  plugins: [svelte()],
}));
writeFileSync(out("demo.js"), demo);
console.log("✓ demo.js");
