// GENERATED by characters/build.mjs — edit characters/src/* and rebuild.
// characters/src/demo-title-entry.js
import { mount } from "https://esm.sh/svelte@5.16.0";

// characters/src/DemoTitle.svelte
import "https://esm.sh/svelte@5.16.0/internal/disclose-version";
import * as $ from "https://esm.sh/svelte@5.16.0/internal/client";
import * as chars from "./browser.js";
var root_3 = $.template(`<!> <!> <!> <!> <!> <!> <!> <!> <!> <!> <!> <!> <!> <!> <!>`, 1);
function DemoTitle($$anchor, $$props) {
  $.push($$props, true);
  const {
    Game,
    Scene,
    Sprite,
    TileSprite,
    Rectangle,
    Text
  } = chars;
  const W = 256, H = 480;
  function preload(scene) {
    scene.load.image("title_bg", "./assets/title_bg_2028.png");
    scene.load.atlas("title_ui", "./assets/title_ui_2028.png", "./assets/title_ui_2028.json");
  }
  let startVisible = $.state(true);
  $.user_effect(() => {
    const t = setInterval(() => $.set(startVisible, !$.get(startVisible)), 500);
    return () => clearInterval(t);
  });
  const startGame = () => {
    location.href = "../phaser-game.html?lowmode=1";
  };
  Game($$anchor, {
    width: W,
    height: H,
    parent: "app",
    backgroundColor: "#000000",
    pixelArt: true,
    children: ($$anchor2, $$slotProps) => {
      {
        const loading = ($$anchor3, progress = $.noop) => {
          var text = $.derived(() => `loading ${Math.round(progress() * 100)}%`);
          Text($$anchor3, {
            x: 128,
            y: 240,
            originX: 0.5,
            originY: 0.5,
            color: "#9ca3af",
            fontSize: 12,
            get text() {
              return $.get(text);
            }
          });
        };
        Scene($$anchor2, {
          key: "title",
          preload,
          loading,
          children: ($$anchor3, $$slotProps2) => {
            var fragment_3 = root_3();
            var node = $.first_child(fragment_3);
            Sprite(node, {
              texture: "title_bg",
              x: 0,
              y: 0,
              originX: 0,
              originY: 0,
              scale: 256 / 768
            });
            var node_1 = $.sibling(node, 2);
            Sprite(node_1, {
              texture: "title_ui",
              frame: "titleG",
              x: 5,
              y: 20,
              originX: 0,
              originY: 0
            });
            var node_2 = $.sibling(node_1, 2);
            $.component(node_2, () => chars.red_dress_killer, ($$anchor4, $$component) => {
              $$component($$anchor4, { x: 120, y: 220, scale: 0.6 });
            });
            var node_3 = $.sibling(node_2, 2);
            Sprite(node_3, {
              texture: "title_ui",
              frame: "logo",
              x: 128,
              y: 75
            });
            var node_4 = $.sibling(node_3, 2);
            Sprite(node_4, {
              texture: "title_ui",
              frame: "subTitleEn",
              x: 128,
              y: 130
            });
            var node_5 = $.sibling(node_4, 2);
            Rectangle(node_5, {
              x: 0,
              y: 360,
              originX: 0,
              originY: 0,
              width: W,
              height: 120,
              fillColor: 0
            });
            var node_6 = $.sibling(node_5, 2);
            Sprite(node_6, {
              texture: "title_ui",
              frame: "titleStartText",
              x: 128,
              y: 330,
              get visible() {
                return $.get(startVisible);
              },
              interactive: true,
              onpointerup: startGame
            });
            var node_7 = $.sibling(node_6, 2);
            Text(node_7, {
              x: 32,
              y: 366,
              text: "WORLD BEST",
              color: "#ffffff",
              stroke: "#000000",
              strokeThickness: 2,
              fontFamily: "Arial",
              fontSize: 11,
              fontStyle: "bold"
            });
            var node_8 = $.sibling(node_7, 2);
            Sprite(node_8, {
              texture: "title_ui",
              frame: "hiScoreTxt",
              x: 32,
              y: 382,
              originX: 0,
              originY: 0
            });
            var node_9 = $.sibling(node_8, 2);
            Text(node_9, {
              x: 110,
              y: 389,
              originY: 0.5,
              text: "0",
              color: "#ffffff",
              stroke: "#000000",
              strokeThickness: 2,
              fontFamily: "Arial",
              fontSize: 16,
              fontStyle: "bold"
            });
            var node_10 = $.sibling(node_9, 2);
            Text(node_10, {
              x: 32,
              y: 404,
              text: "WORLD BEST STANDBY",
              color: "#9be37f",
              stroke: "#000000",
              strokeThickness: 2,
              fontFamily: "Arial",
              fontSize: 8,
              fontStyle: "bold"
            });
            var node_11 = $.sibling(node_10, 2);
            Sprite(node_11, {
              texture: "title_ui",
              frame: "twitterBtn0",
              x: 128,
              y: 428
            });
            var node_12 = $.sibling(node_11, 2);
            Sprite(node_12, {
              texture: "title_ui",
              frame: "titleCopyright",
              x: 0,
              y: 440,
              originX: 0,
              originY: 0
            });
            var node_13 = $.sibling(node_12, 2);
            Sprite(node_13, {
              texture: "title_ui",
              frame: "howtoBtn0",
              x: 15,
              y: 10,
              originX: 0,
              originY: 0
            });
            var node_14 = $.sibling(node_13, 2);
            Sprite(node_14, {
              texture: "title_ui",
              frame: "staffrollBtn0",
              x: 241,
              y: 10,
              originX: 1,
              originY: 0
            });
            $.append($$anchor3, fragment_3);
          },
          $$slots: { loading: true, default: true }
        });
      }
    },
    $$slots: { default: true }
  });
  $.pop();
}

// characters/src/demo-title-entry.js
mount(DemoTitle, { target: document.getElementById("app") });
