// GENERATED by characters/build.mjs — edit characters/src/* and rebuild.
// characters/src/demo-entry.js
import { mount } from "https://esm.sh/svelte@5.16.0";

// characters/src/Demo.svelte
import "https://esm.sh/svelte@5.16.0/internal/disclose-version";
import * as $ from "https://esm.sh/svelte@5.16.0/internal/client";
import * as chars from "./browser.js";
var root_2 = $.template(`<!> <!> <!> <!> <!> <!>`, 1);
function Demo($$anchor) {
  const { Game, Scene, Text } = chars;
  let status = $.state("loading characters from the library\u2026");
  let ready = 0;
  const loaded = (name) => () => {
    ready++;
    $.set(status, `${ready}/3 loaded (${name} ready)`);
    if (ready === 3) $.set(status, "red_dress_killer, weirdo & dukeNukem \u2014 live from /characters");
  };
  const failed = (e) => $.set(status, `load failed: ${e.message || e}`);
  Game($$anchor, {
    width: 480,
    height: 640,
    parent: "app",
    backgroundColor: "#0b0b12",
    children: ($$anchor2, $$slotProps) => {
      Scene($$anchor2, {
        key: "characters",
        children: ($$anchor3, $$slotProps2) => {
          var fragment_2 = root_2();
          var node = $.first_child(fragment_2);
          Text(node, {
            x: 12,
            y: 10,
            text: "import { red_dress_killer } from",
            color: "#9ca3af",
            fontSize: 13
          });
          var node_1 = $.sibling(node, 2);
          Text(node_1, {
            x: 12,
            y: 28,
            text: "'https://easierbycode.com/2019-es7/characters'",
            color: "#84cc16",
            fontSize: 13
          });
          var node_2 = $.sibling(node_1, 2);
          Text(node_2, {
            x: 12,
            y: 606,
            get text() {
              return $.get(status);
            },
            color: "#e5e7eb",
            fontSize: 12
          });
          var node_3 = $.sibling(node_2, 2);
          var onready = $.derived(() => loaded("red_dress_killer"));
          $.component(node_3, () => chars.red_dress_killer, ($$anchor4, $$component) => {
            $$component($$anchor4, {
              x: 130,
              y: 300,
              get onready() {
                return $.get(onready);
              },
              onerror: failed
            });
          });
          var node_4 = $.sibling(node_3, 2);
          var onready_1 = $.derived(() => loaded("weirdo"));
          $.component(node_4, () => chars.weirdo, ($$anchor4, $$component) => {
            $$component($$anchor4, {
              x: 350,
              y: 300,
              get onready() {
                return $.get(onready_1);
              },
              onerror: failed
            });
          });
          var node_5 = $.sibling(node_4, 2);
          var onready_2 = $.derived(() => loaded("dukeNukem"));
          $.component(node_5, () => chars.dukeNukem, ($$anchor4, $$component) => {
            $$component($$anchor4, {
              x: 240,
              y: 500,
              scale: 2,
              get onready() {
                return $.get(onready_2);
              },
              onerror: failed
            });
          });
          $.append($$anchor3, fragment_2);
        },
        $$slots: { default: true }
      });
    },
    $$slots: { default: true }
  });
}

// characters/src/demo-entry.js
mount(Demo, { target: document.getElementById("app") });
