// GENERATED by characters/build.mjs — edit characters/src/* and rebuild.
// node_modules/5velte-ph4ser/src/Game.svelte
import "svelte/internal/disclose-version";
import * as $ from "svelte/internal/client";

// node_modules/5velte-ph4ser/src/core/hooks.ts
import Phaser from "phaser";
import {
  getAllContexts,
  mount,
  onDestroy as onDestroy2,
  setContext as setContext2,
  unmount
} from "svelte";
import { writable, readonly } from "svelte/store";

// node_modules/5velte-ph4ser/src/core/apply.ts
function apply(cache, key, value, setter) {
  if (value === void 0) {
    return;
  }
  if (cache) {
    if (cache[key] === value) {
      return;
    }
    cache[key] = value;
  }
  setter(value);
}
function applyGameObjectProps(instance, props, cache) {
  const go = instance;
  apply(cache, "name", props.name, (v) => go.setName(v));
  apply(cache, "active", props.active, (v) => go.setActive(v));
  if (typeof go.setX === "function") {
    apply(cache, "x", props.x, (v) => go.setX(v));
    apply(cache, "y", props.y, (v) => go.setY(v));
    apply(cache, "z", props.z, (v) => go.setZ(v));
    apply(cache, "w", props.w, (v) => go.setW(v));
    apply(cache, "scale", props.scale, (v) => go.setScale(v));
    apply(cache, "scaleX", props.scaleX, (v) => {
      go.scaleX = v;
    });
    apply(cache, "scaleY", props.scaleY, (v) => {
      go.scaleY = v;
    });
    apply(cache, "angle", props.angle, (v) => go.setAngle(v));
    apply(cache, "rotation", props.rotation, (v) => go.setRotation(v));
  }
  if (typeof go.setDepth === "function") {
    apply(cache, "depth", props.depth, (v) => go.setDepth(v));
  }
  if (typeof go.setAlpha === "function") {
    apply(cache, "alpha", props.alpha, (v) => go.setAlpha(v));
  }
  if (typeof go.setBlendMode === "function") {
    apply(cache, "blendMode", props.blendMode, (v) => go.setBlendMode(v));
  }
  if (typeof go.setFlipX === "function") {
    apply(cache, "flipX", props.flipX, (v) => go.setFlipX(v));
    apply(cache, "flipY", props.flipY, (v) => go.setFlipY(v));
  }
  if (typeof go.setOrigin === "function") {
    apply(cache, "originX", props.originX, (v) => go.setOrigin(v, go.originY));
    apply(cache, "originY", props.originY, (v) => go.setOrigin(go.originX, v));
  }
  if (typeof go.setScrollFactor === "function") {
    apply(
      cache,
      "scrollFactorX",
      props.scrollFactorX,
      (v) => go.setScrollFactor(v, go.scrollFactorY)
    );
    apply(
      cache,
      "scrollFactorY",
      props.scrollFactorY,
      (v) => go.setScrollFactor(go.scrollFactorX, v)
    );
  }
  if (typeof go.setVisible === "function") {
    apply(cache, "visible", props.visible, (v) => go.setVisible(v));
  }
  if (typeof go.setTint === "function") {
    apply(cache, "tint", props.tint, (v) => go.setTint(v));
  }
  apply(cache, "interactive", props.interactive, (v) => {
    if (v === true) {
      go.setInteractive();
    } else if (v === false) {
      go.disableInteractive();
    } else if (v) {
      go.setInteractive(v.shape, v.callback, v.dropZone);
    }
  });
}
function applySpriteProps(instance, props, cache) {
  applyGameObjectProps(instance, props, cache);
  apply(cache, "texture", props.texture, (v) => {
    if (instance.texture.key !== v) {
      instance.setTexture(v, props.frame);
    }
  });
  apply(cache, "animation", props.animation, (v) => instance.anims.play(v, true));
}
function applyTextProps(instance, props, cache) {
  applyGameObjectProps(instance, props, cache);
  apply(cache, "text", props.text, (v) => instance.setText(v));
  apply(cache, "align", props.align, (v) => instance.setAlign(v));
  apply(cache, "color", props.color, (v) => instance.setColor(v));
  apply(cache, "fontFamily", props.fontFamily, (v) => instance.setFontFamily(v));
  apply(cache, "fontSize", props.fontSize, (v) => instance.setFontSize(v));
  apply(cache, "fontStyle", props.fontStyle, (v) => instance.setFontStyle(v));
  apply(
    cache,
    "backgroundColor",
    props.backgroundColor,
    (v) => instance.setBackgroundColor(v)
  );
  apply(
    cache,
    "stroke",
    props.stroke,
    (v) => instance.setStroke(v, props.strokeThickness ?? 1)
  );
  apply(cache, "lineSpacing", props.lineSpacing, (v) => instance.setLineSpacing(v));
  apply(
    cache,
    "padding",
    props.padding,
    (v) => instance.setPadding(v)
  );
  apply(
    cache,
    "wordWrapWidth",
    props.wordWrapWidth,
    (v) => instance.setWordWrapWidth(v)
  );
}
function applyTileSpriteProps(instance, props, cache) {
  applyGameObjectProps(instance, props, cache);
  apply(cache, "tilePositionX", props.tilePositionX, (v) => {
    instance.tilePositionX = v;
  });
  apply(cache, "tilePositionY", props.tilePositionY, (v) => {
    instance.tilePositionY = v;
  });
  apply(cache, "tileScaleX", props.tileScaleX, (v) => {
    instance.tileScaleX = v;
  });
  apply(cache, "tileScaleY", props.tileScaleY, (v) => {
    instance.tileScaleY = v;
  });
}
function applyRectangleProps(instance, props, cache) {
  applyGameObjectProps(instance, props, cache);
  apply(
    cache,
    "fillColor",
    props.fillColor,
    (v) => instance.setFillStyle(v, props.fillAlpha)
  );
  apply(
    cache,
    "strokeColor",
    props.strokeColor,
    (v) => instance.setStrokeStyle(props.strokeWidth ?? 1, v)
  );
  apply(cache, "width", props.width, (v) => instance.setSize(v, instance.height));
  apply(cache, "height", props.height, (v) => instance.setSize(instance.width, v));
}
function applyContainerProps(instance, props, cache) {
  applyGameObjectProps(instance, props, cache);
  apply(cache, "width", props.width, (v) => instance.setSize(v, instance.height));
  apply(cache, "height", props.height, (v) => instance.setSize(instance.width, v));
}
function applyArcadeBodyProps(instance, props, cache) {
  const body = instance.body;
  apply(
    cache,
    "circle",
    props.circle,
    (v) => body.setCircle(v.radius, v.offsetX, v.offsetY)
  );
  if (props.circle === void 0) {
    apply(
      cache,
      "width",
      props.width,
      (v) => body.setSize(v, props.height, props.center)
    );
    apply(
      cache,
      "height",
      props.height,
      (v) => body.setSize(props.width, v, props.center)
    );
  }
  apply(cache, "offsetX", props.offsetX, (v) => body.setOffset(v, body.offset.y));
  apply(cache, "offsetY", props.offsetY, (v) => body.setOffset(body.offset.x, v));
  apply(cache, "acceleration", props.acceleration, (v) => body.setAcceleration(v, v));
  apply(cache, "accelerationX", props.accelerationX, (v) => body.setAccelerationX(v));
  apply(cache, "accelerationY", props.accelerationY, (v) => body.setAccelerationY(v));
  apply(cache, "allowDrag", props.allowDrag, (v) => {
    body.allowDrag = v;
  });
  apply(cache, "allowGravity", props.allowGravity, (v) => body.setAllowGravity(v));
  apply(cache, "allowRotation", props.allowRotation, (v) => {
    body.allowRotation = v;
  });
  apply(
    cache,
    "angularAcceleration",
    props.angularAcceleration,
    (v) => body.setAngularAcceleration(v)
  );
  apply(cache, "angularDrag", props.angularDrag, (v) => body.setAngularDrag(v));
  apply(
    cache,
    "angularVelocity",
    props.angularVelocity,
    (v) => body.setAngularVelocity(v)
  );
  apply(cache, "bounce", props.bounce, (v) => body.setBounce(v, v));
  apply(cache, "bounceX", props.bounceX, (v) => body.setBounceX(v));
  apply(cache, "bounceY", props.bounceY, (v) => body.setBounceY(v));
  apply(
    cache,
    "collideWorldBounds",
    props.collideWorldBounds,
    (v) => body.setCollideWorldBounds(v)
  );
  apply(cache, "drag", props.drag, (v) => body.setDrag(v, v));
  apply(cache, "dragX", props.dragX, (v) => body.setDragX(v));
  apply(cache, "dragY", props.dragY, (v) => body.setDragY(v));
  apply(cache, "friction", props.friction, (v) => body.setFriction(v, v));
  apply(cache, "frictionX", props.frictionX, (v) => body.setFrictionX(v));
  apply(cache, "frictionY", props.frictionY, (v) => body.setFrictionY(v));
  apply(cache, "gravity", props.gravity, (v) => body.setGravity(v, v));
  apply(cache, "gravityX", props.gravityX, (v) => body.setGravityX(v));
  apply(cache, "gravityY", props.gravityY, (v) => body.setGravityY(v));
  apply(cache, "immovable", props.immovable, (v) => body.setImmovable(v));
  apply(cache, "mass", props.mass, (v) => body.setMass(v));
  apply(cache, "maxAngular", props.maxAngular, (v) => {
    body.maxAngular = v;
  });
  apply(cache, "maxSpeed", props.maxSpeed, (v) => body.setMaxSpeed(v));
  apply(cache, "maxVelocityX", props.maxVelocityX, (v) => {
    body.maxVelocity.x = v;
  });
  apply(cache, "maxVelocityY", props.maxVelocityY, (v) => {
    body.maxVelocity.y = v;
  });
  apply(cache, "onWorldBounds", props.onWorldBounds, (v) => {
    body.onWorldBounds = v;
  });
  apply(cache, "pushable", props.pushable, (v) => {
    body.pushable = v;
  });
  apply(cache, "useDamping", props.useDamping, (v) => {
    body.useDamping = v;
  });
  apply(cache, "velocity", props.velocity, (v) => body.setVelocity(v, v));
  apply(cache, "velocityX", props.velocityX, (v) => body.setVelocityX(v));
  apply(cache, "velocityY", props.velocityY, (v) => body.setVelocityY(v));
}

// node_modules/5velte-ph4ser/src/core/attach.ts
import { onDestroy, setContext } from "svelte";

// node_modules/5velte-ph4ser/src/core/context.ts
import { getContext } from "svelte";
var GAME_CONTEXT_KEY = "phaser/game";
var SCENE_CONTEXT_KEY = "phaser/scene";
var GAME_OBJECT_CONTEXT_KEY = "phaser/game-object";
var CONTAINER_CONTEXT_KEY = "phaser/container";
var SPAWNER_CONTEXT_KEY = "phaser/spawner";
function getGame() {
  return getContext(GAME_CONTEXT_KEY);
}
function getScene() {
  return getContext(SCENE_CONTEXT_KEY);
}
function getGameObject() {
  return getContext(GAME_OBJECT_CONTEXT_KEY);
}
function getContainer() {
  return getContext(CONTAINER_CONTEXT_KEY);
}
function getSpawner() {
  return getContext(SPAWNER_CONTEXT_KEY);
}

// node_modules/5velte-ph4ser/src/core/attach.ts
var POINTER_EVENTS = [
  "pointerdown",
  "pointerup",
  "pointermove",
  "pointerover",
  "pointerout",
  "drag",
  "dragstart",
  "dragend",
  "dragenter",
  "dragleave",
  "dragover",
  "drop"
];
var SPRITE_ANIMATION_EVENTS = [
  "animationstart",
  "animationcomplete",
  "animationrepeat",
  "animationstop"
];
function attachGameObject(instance, getProps) {
  const scene = getScene();
  const container = getContainer();
  setContext(GAME_OBJECT_CONTEXT_KEY, instance);
  const name = getProps().name;
  if (name !== void 0) {
    instance.setName(name);
  }
  scene.add.existing(instance);
  if (container && container !== instance) {
    container.add(instance);
  }
  for (const event of POINTER_EVENTS) {
    instance.on(event, (...args) => {
      const handler = getProps()[`on${event}`];
      if (typeof handler === "function") {
        handler(...args);
      }
    });
  }
  onDestroy(() => {
    instance.destroy();
  });
  return instance;
}
function attachSpriteAnimationEvents(instance, getProps) {
  for (const event of SPRITE_ANIMATION_EVENTS) {
    instance.on(event, (...args) => {
      const handler = getProps()[`on${event}`];
      if (typeof handler === "function") {
        handler(...args);
      }
    });
  }
}

// node_modules/5velte-ph4ser/src/core/util.ts
function removeUndefined(object) {
  const result = {};
  for (const key of Object.keys(object)) {
    if (typeof object[key] !== "undefined") {
      result[key] = object[key];
    }
  }
  return result;
}
function toArray(value) {
  return Array.isArray(value) ? value : [value];
}
function isDestroyed(instance) {
  return !instance.scene;
}
function findGameObjectsByName(scene, name) {
  return scene.children.list.filter((child) => child.name === name);
}

// node_modules/5velte-ph4ser/src/core/hooks.ts
function createGame(options = {}) {
  const { instance, onpreboot, onpostboot, ...config } = options;
  const game = instance ?? new Phaser.Game({
    ...removeUndefined(config),
    callbacks: {
      preBoot: (g) => onpreboot?.(g),
      postBoot: (g) => onpostboot?.(g)
    }
  });
  setContext2(GAME_CONTEXT_KEY, game);
  const booted = writable(game.isRunning);
  if (!game.isRunning) {
    game.events.once("ready", () => booted.set(true));
  }
  onDestroy2(() => {
    game.destroy(true);
  });
  return { game, booted: readonly(booted) };
}
function createScene(options) {
  const { key, instance, preload, create, init, ...settings } = options;
  const game = getGame();
  const scene = instance ?? new Phaser.Scene(
    removeUndefined({ key, ...settings })
  );
  setContext2(SCENE_CONTEXT_KEY, scene);
  const loading = writable(!!preload);
  const progress = writable(0);
  scene.preload = preload ? () => preload(scene) : void 0;
  scene.create = create ? () => create(scene) : void 0;
  scene.init = init ? () => init(scene) : void 0;
  game.scene.add(key, scene, true);
  scene.load.on("progress", (value) => progress.set(value));
  scene.load.on("complete", () => {
    progress.set(1);
    loading.set(false);
  });
  onDestroy2(() => {
    game.scene.remove(key);
  });
  return { scene, loading: readonly(loading), progress: readonly(progress) };
}
function createSpawner() {
  const spawner = {
    spawn(component, props = {}) {
      const target = document.createElement("div");
      const app = mount(component, {
        target,
        context,
        props: {
          ...props,
          onDestroy: () => {
            if (mounted.delete(app)) {
              unmount(app);
            }
          }
        }
      });
      mounted.add(app);
    }
  };
  setContext2(SPAWNER_CONTEXT_KEY, spawner);
  const context = getAllContexts();
  const mounted = /* @__PURE__ */ new Set();
  onDestroy2(() => {
    for (const app of mounted) {
      unmount(app);
    }
    mounted.clear();
  });
  return spawner;
}
function syncProps(instance, getProps, applier) {
  const game = getGame();
  const cache = {};
  applier(instance, getProps(), cache);
  const listener = () => applier(instance, getProps(), cache);
  game.events.on("prestep", listener);
  onDestroy2(() => {
    game.events.off("prestep", listener);
  });
}
function useSprite(getProps = () => ({})) {
  const scene = getScene();
  const props = getProps();
  const sprite = new Phaser.GameObjects.Sprite(
    scene,
    props.x ?? 0,
    props.y ?? 0,
    props.texture ?? "__DEFAULT",
    props.frame
  );
  attachGameObject(sprite, getProps);
  attachSpriteAnimationEvents(sprite, getProps);
  syncProps(sprite, getProps, applySpriteProps);
  return sprite;
}
function useText(getProps = () => ({})) {
  const scene = getScene();
  const props = getProps();
  const text = new Phaser.GameObjects.Text(
    scene,
    props.x ?? 0,
    props.y ?? 0,
    props.text ?? "",
    {}
  );
  attachGameObject(text, getProps);
  syncProps(text, getProps, applyTextProps);
  return text;
}
function useTileSprite(getProps = () => ({})) {
  const scene = getScene();
  const props = getProps();
  const tileSprite = new Phaser.GameObjects.TileSprite(
    scene,
    props.x ?? 0,
    props.y ?? 0,
    props.width ?? 0,
    props.height ?? 0,
    props.texture ?? "",
    props.frame
  );
  attachGameObject(tileSprite, getProps);
  syncProps(tileSprite, getProps, applyTileSpriteProps);
  return tileSprite;
}
function useRectangle(getProps = () => ({})) {
  const scene = getScene();
  const props = getProps();
  const rectangle = new Phaser.GameObjects.Rectangle(
    scene,
    props.x ?? 0,
    props.y ?? 0,
    props.width ?? 0,
    props.height ?? 0,
    props.fillColor,
    props.fillAlpha
  );
  attachGameObject(rectangle, getProps);
  syncProps(rectangle, getProps, applyRectangleProps);
  return rectangle;
}
function useContainer(getProps = () => ({})) {
  const scene = getScene();
  const props = getProps();
  const container = new Phaser.GameObjects.Container(
    scene,
    props.x ?? 0,
    props.y ?? 0,
    []
  );
  attachGameObject(container, getProps);
  syncProps(container, getProps, applyContainerProps);
  return container;
}
function useArcadePhysics(getProps = () => ({}), gameObject) {
  const scene = getScene();
  const instance = gameObject ?? getGameObject();
  const { bodyType = "dynamic", onWorldBounds = true } = getProps();
  scene.physics.world.enable(
    instance,
    bodyType === "static" ? Phaser.Physics.Arcade.STATIC_BODY : Phaser.Physics.Arcade.DYNAMIC_BODY
  );
  syncProps(instance, () => ({ onWorldBounds, ...getProps() }), applyArcadeBodyProps);
  onDestroy2(() => {
    if (scene.children.exists(instance)) {
      scene.physics.world.disable(instance);
    }
  });
  return instance.body;
}
function useArcadeCollider(props, gameObject) {
  const scene = getScene();
  const parent = gameObject ?? getGameObject();
  function resolveTargets() {
    return toArray(props.with).flatMap(
      (target) => typeof target === "string" ? findGameObjectsByName(scene, target) : target
    );
  }
  const collideCallback = (self, other) => props.oncollide?.({ self, other });
  const processCallback = props.allowCollision ? (self, other) => props.allowCollision({ self, other }) : void 0;
  const collider = props.overlapOnly ? scene.physics.add.overlap(
    [parent],
    resolveTargets(),
    collideCallback,
    processCallback
  ) : scene.physics.add.collider(
    [parent],
    resolveTargets(),
    collideCallback,
    processCallback
  );
  function handleAddedToScene(object) {
    if (!object.name) return;
    const names = toArray(props.with).filter((t) => typeof t === "string");
    if (names.includes(object.name)) {
      collider.object2 = [
        ...collider.object2,
        object
      ];
    }
  }
  scene.events.on(Phaser.Scenes.Events.ADDED_TO_SCENE, handleAddedToScene);
  onDestroy2(() => {
    scene.events.off(Phaser.Scenes.Events.ADDED_TO_SCENE, handleAddedToScene);
    collider.destroy();
  });
  return collider;
}

// node_modules/5velte-ph4ser/src/Game.svelte
function Game($$anchor, $$props) {
  $.push($$props, true);
  const $$stores = $.setup_stores();
  const $booted = () => $.store_get(booted, "$booted", $$stores);
  let instance = $.prop($$props, "instance", 15), config = $.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "booting",
    "children"
  ]);
  const { game, booted } = createGame({ ...config, instance: instance() });
  instance(game);
  var fragment = $.comment();
  var node = $.first_child(fragment);
  {
    var consequent = ($$anchor2) => {
      var fragment_1 = $.comment();
      var node_1 = $.first_child(fragment_1);
      $.snippet(node_1, () => $$props.children ?? $.noop);
      $.append($$anchor2, fragment_1);
    };
    var alternate = ($$anchor2) => {
      var fragment_2 = $.comment();
      var node_2 = $.first_child(fragment_2);
      $.snippet(node_2, () => $$props.booting ?? $.noop);
      $.append($$anchor2, fragment_2);
    };
    $.if(node, ($$render) => {
      if ($booted()) $$render(consequent);
      else $$render(alternate, false);
    });
  }
  $.append($$anchor, fragment);
  $.pop();
}

// node_modules/5velte-ph4ser/src/Scene.svelte
import "svelte/internal/disclose-version";
import * as $2 from "svelte/internal/client";
function Scene($$anchor, $$props) {
  $2.push($$props, true);
  const $$stores = $2.setup_stores();
  const $isLoading = () => $2.store_get(isLoading, "$isLoading", $$stores);
  const $progress = () => $2.store_get(progress, "$progress", $$stores);
  let instance = $2.prop($$props, "instance", 15), options = $2.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "loading",
    "children"
  ]);
  const { scene, loading: isLoading, progress } = createScene({ ...options, instance: instance() });
  instance(scene);
  var fragment = $2.comment();
  var node = $2.first_child(fragment);
  {
    var consequent = ($$anchor2) => {
      var fragment_1 = $2.comment();
      var node_1 = $2.first_child(fragment_1);
      $2.snippet(node_1, () => $$props.loading ?? $2.noop, $progress);
      $2.append($$anchor2, fragment_1);
    };
    var alternate = ($$anchor2) => {
      var fragment_2 = $2.comment();
      var node_2 = $2.first_child(fragment_2);
      $2.snippet(node_2, () => $$props.children ?? $2.noop);
      $2.append($$anchor2, fragment_2);
    };
    $2.if(node, ($$render) => {
      if ($isLoading()) $$render(consequent);
      else $$render(alternate, false);
    });
  }
  $2.append($$anchor, fragment);
  $2.pop();
}

// node_modules/5velte-ph4ser/src/Spawner.svelte
import "svelte/internal/disclose-version";
import * as $3 from "svelte/internal/client";
function Spawner($$anchor, $$props) {
  $3.push($$props, true);
  createSpawner();
  var fragment = $3.comment();
  var node = $3.first_child(fragment);
  $3.snippet(node, () => $$props.children ?? $3.noop);
  $3.append($$anchor, fragment);
  $3.pop();
}

// node_modules/5velte-ph4ser/src/Sprite.svelte
import "svelte/internal/disclose-version";
import * as $6 from "svelte/internal/client";
import Phaser2 from "phaser";

// node_modules/5velte-ph4ser/src/gameObject.svelte.js
import * as $5 from "svelte/internal/client";

// node_modules/5velte-ph4ser/src/util.svelte.js
import * as $4 from "svelte/internal/client";
import { untrack } from "svelte";
function bindProp(get2, apply2) {
  let last = get2();
  if (last !== void 0) {
    apply2(last);
  }
  $4.user_effect(() => {
    const value = get2();
    if (value !== void 0 && value !== last) {
      last = value;
      untrack(() => apply2(value));
    }
  });
}

// node_modules/5velte-ph4ser/src/gameObject.svelte.js
function useGameObject(instance, props) {
  attachGameObject(instance, props);
  const go = instance;
  bindProp(() => props().name, (v) => go.setName(v));
  bindProp(() => props().active, (v) => go.setActive(v));
  if (typeof go.setX === "function") {
    bindProp(() => props().x, (v) => go.setX(v));
    bindProp(() => props().y, (v) => go.setY(v));
    bindProp(() => props().z, (v) => go.setZ(v));
    bindProp(() => props().w, (v) => go.setW(v));
    bindProp(() => props().scale, (v) => go.setScale(v));
    bindProp(() => props().scaleX, (v) => {
      go.scaleX = v;
    });
    bindProp(() => props().scaleY, (v) => {
      go.scaleY = v;
    });
    bindProp(() => props().angle, (v) => go.setAngle(v));
    bindProp(() => props().rotation, (v) => go.setRotation(v));
  }
  if (typeof go.setDepth === "function") {
    bindProp(() => props().depth, (v) => go.setDepth(v));
  }
  if (typeof go.setAlpha === "function") {
    bindProp(() => props().alpha, (v) => go.setAlpha(v));
  }
  if (typeof go.setBlendMode === "function") {
    bindProp(() => props().blendMode, (v) => go.setBlendMode(v));
  }
  if (typeof go.setFlipX === "function") {
    bindProp(() => props().flipX, (v) => go.setFlipX(v));
    bindProp(() => props().flipY, (v) => go.setFlipY(v));
  }
  if (typeof go.setOrigin === "function") {
    bindProp(() => props().originX, (v) => go.setOrigin(v, go.originY));
    bindProp(() => props().originY, (v) => go.setOrigin(go.originX, v));
  }
  if (typeof go.setScrollFactor === "function") {
    bindProp(() => props().scrollFactorX, (v) => go.setScrollFactor(v, go.scrollFactorY));
    bindProp(() => props().scrollFactorY, (v) => go.setScrollFactor(go.scrollFactorX, v));
  }
  if (typeof go.setVisible === "function") {
    bindProp(() => props().visible, (v) => go.setVisible(v));
  }
  if (typeof go.setTint === "function") {
    bindProp(() => props().tint, (v) => go.setTint(v));
  }
  bindProp(() => props().interactive, (v) => {
    if (v === true) {
      go.setInteractive();
    } else if (v === false) {
      go.disableInteractive();
    } else if (v) {
      go.setInteractive(v.shape, v.callback, v.dropZone);
    }
  });
}

// node_modules/5velte-ph4ser/src/Sprite.svelte
function Sprite($$anchor, $$props) {
  $6.push($$props, true);
  let instance = $6.prop($$props, "instance", 15), rest = $6.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "children"
  ]);
  const scene = getScene();
  if (!instance() || isDestroyed(instance())) {
    instance(new Phaser2.GameObjects.Sprite(scene, $$props.x ?? 0, $$props.y ?? 0, $$props.texture ?? "__DEFAULT", $$props.frame));
  }
  const sprite = instance();
  useGameObject(sprite, () => rest);
  attachSpriteAnimationEvents(sprite, () => rest);
  bindProp(() => $$props.texture, (v) => {
    if (sprite.texture.key !== v) {
      sprite.setTexture(v, $$props.frame);
    }
  });
  bindProp(() => $$props.animation, (v) => sprite.anims.play(v, true));
  var fragment = $6.comment();
  var node = $6.first_child(fragment);
  $6.snippet(node, () => $$props.children ?? $6.noop);
  $6.append($$anchor, fragment);
  $6.pop();
}

// node_modules/5velte-ph4ser/src/Text.svelte
import "svelte/internal/disclose-version";
import * as $7 from "svelte/internal/client";
import Phaser3 from "phaser";
function Text($$anchor, $$props) {
  $7.push($$props, true);
  let instance = $7.prop($$props, "instance", 15), rest = $7.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "children"
  ]);
  const scene = getScene();
  if (!instance() || isDestroyed(instance())) {
    instance(new Phaser3.GameObjects.Text(scene, $$props.x ?? 0, $$props.y ?? 0, $$props.text ?? "", {}));
  }
  const textObject = instance();
  useGameObject(textObject, () => rest);
  bindProp(() => $$props.text, (v) => textObject.setText(v));
  bindProp(() => $$props.align, (v) => textObject.setAlign(v));
  bindProp(() => $$props.color, (v) => textObject.setColor(v));
  bindProp(() => $$props.fontFamily, (v) => textObject.setFontFamily(v));
  bindProp(() => $$props.fontSize, (v) => textObject.setFontSize(v));
  bindProp(() => $$props.fontStyle, (v) => textObject.setFontStyle(v));
  bindProp(() => $$props.backgroundColor, (v) => textObject.setBackgroundColor(v));
  bindProp(() => $$props.stroke, (v) => textObject.setStroke(v, $$props.strokeThickness ?? 1));
  bindProp(() => $$props.lineSpacing, (v) => textObject.setLineSpacing(v));
  bindProp(() => $$props.padding, (v) => textObject.setPadding(v));
  bindProp(() => $$props.wordWrapWidth, (v) => textObject.setWordWrapWidth(v));
  var fragment = $7.comment();
  var node = $7.first_child(fragment);
  $7.snippet(node, () => $$props.children ?? $7.noop);
  $7.append($$anchor, fragment);
  $7.pop();
}

// node_modules/5velte-ph4ser/src/TileSprite.svelte
import "svelte/internal/disclose-version";
import * as $8 from "svelte/internal/client";
import Phaser4 from "phaser";
function TileSprite($$anchor, $$props) {
  $8.push($$props, true);
  let instance = $8.prop($$props, "instance", 15), rest = $8.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "children"
  ]);
  const scene = getScene();
  if (!instance() || isDestroyed(instance())) {
    instance(new Phaser4.GameObjects.TileSprite(scene, $$props.x ?? 0, $$props.y ?? 0, $$props.width ?? 0, $$props.height ?? 0, $$props.texture ?? "", $$props.frame));
  }
  const tileSprite = instance();
  useGameObject(tileSprite, () => rest);
  bindProp(() => $$props.tilePositionX, (v) => {
    tileSprite.tilePositionX = v;
  });
  bindProp(() => $$props.tilePositionY, (v) => {
    tileSprite.tilePositionY = v;
  });
  bindProp(() => $$props.tileScaleX, (v) => {
    tileSprite.tileScaleX = v;
  });
  bindProp(() => $$props.tileScaleY, (v) => {
    tileSprite.tileScaleY = v;
  });
  var fragment = $8.comment();
  var node = $8.first_child(fragment);
  $8.snippet(node, () => $$props.children ?? $8.noop);
  $8.append($$anchor, fragment);
  $8.pop();
}

// node_modules/5velte-ph4ser/src/Rectangle.svelte
import "svelte/internal/disclose-version";
import * as $9 from "svelte/internal/client";
import Phaser5 from "phaser";
function Rectangle($$anchor, $$props) {
  $9.push($$props, true);
  let instance = $9.prop($$props, "instance", 15), rest = $9.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "children"
  ]);
  const scene = getScene();
  if (!instance() || isDestroyed(instance())) {
    instance(new Phaser5.GameObjects.Rectangle(scene, $$props.x ?? 0, $$props.y ?? 0, $$props.width ?? 0, $$props.height ?? 0, $$props.fillColor, $$props.fillAlpha));
  }
  const rectangle = instance();
  useGameObject(rectangle, () => rest);
  bindProp(() => $$props.fillColor, (v) => rectangle.setFillStyle(v, $$props.fillAlpha));
  bindProp(() => $$props.strokeColor, (v) => rectangle.setStrokeStyle($$props.strokeWidth ?? 1, v));
  bindProp(() => $$props.width, (v) => rectangle.setSize(v, rectangle.height));
  bindProp(() => $$props.height, (v) => rectangle.setSize(rectangle.width, v));
  var fragment = $9.comment();
  var node = $9.first_child(fragment);
  $9.snippet(node, () => $$props.children ?? $9.noop);
  $9.append($$anchor, fragment);
  $9.pop();
}

// node_modules/5velte-ph4ser/src/Container.svelte
import "svelte/internal/disclose-version";
import * as $10 from "svelte/internal/client";
import Phaser6 from "phaser";
import { setContext as setContext3 } from "svelte";
function Container($$anchor, $$props) {
  $10.push($$props, true);
  let instance = $10.prop($$props, "instance", 15), rest = $10.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "instance",
    "children"
  ]);
  const scene = getScene();
  if (!instance() || isDestroyed(instance())) {
    instance(new Phaser6.GameObjects.Container(scene, $$props.x ?? 0, $$props.y ?? 0, []));
  }
  const container = instance();
  useGameObject(container, () => rest);
  setContext3(CONTAINER_CONTEXT_KEY, container);
  bindProp(() => $$props.width, (v) => container.setSize(v, container.height));
  bindProp(() => $$props.height, (v) => container.setSize(container.width, v));
  var fragment = $10.comment();
  var node = $10.first_child(fragment);
  $10.snippet(node, () => $$props.children ?? $10.noop);
  $10.append($$anchor, fragment);
  $10.pop();
}

// node_modules/5velte-ph4ser/src/ArcadePhysics.svelte
import "svelte/internal/disclose-version";
import * as $11 from "svelte/internal/client";
function ArcadePhysics($$anchor, $$props) {
  $11.push($$props, true);
  let rest = $11.rest_props($$props, [
    "$$slots",
    "$$events",
    "$$legacy",
    "children"
  ]);
  useArcadePhysics(() => rest);
  var fragment = $11.comment();
  var node = $11.first_child(fragment);
  $11.snippet(node, () => $$props.children ?? $11.noop);
  $11.append($$anchor, fragment);
  $11.pop();
}

// node_modules/5velte-ph4ser/src/ArcadeCollider.svelte
import "svelte/internal/disclose-version";
import * as $12 from "svelte/internal/client";
import { untrack as untrack2 } from "svelte";
function ArcadeCollider($$anchor, $$props) {
  $12.push($$props, true);
  const scene = getScene();
  const collider = useArcadeCollider({
    get with() {
      return $$props.with;
    },
    get overlapOnly() {
      return $$props.overlapOnly;
    },
    get oncollide() {
      return $$props.oncollide;
    },
    get allowCollision() {
      return $$props.allowCollision;
    }
  });
  $12.user_effect(() => {
    const value = $$props.with;
    untrack2(() => {
      collider.object2 = toArray(value).flatMap((target) => typeof target === "string" ? findGameObjectsByName(scene, target) : target);
    });
  });
  $12.user_effect(() => {
    collider.overlapOnly = !!$$props.overlapOnly;
  });
  $12.pop();
}

// node_modules/5velte-ph4ser/src/core/events.ts
import { onMount } from "svelte";
function onGameEvent(event, callback) {
  const game = getGame();
  onMount(() => {
    game.events.on(event, callback);
    return () => game.events.off(event, callback);
  });
}
function onSceneEvent(event, callback) {
  const scene = getScene();
  onMount(() => {
    scene.events.on(event, callback);
    return () => scene.events.off(event, callback);
  });
}
function onInputEvent(event, callback) {
  const scene = getScene();
  onMount(() => {
    scene.input.on(event, callback);
    return () => scene.input.off(event, callback);
  });
}
function onArcadePhysicsEvent(event, callback) {
  const scene = getScene();
  onMount(() => {
    scene.physics.world.on(event, callback);
    return () => scene.physics.world.off(event, callback);
  });
}

// characters/src/Character.svelte
import "svelte/internal/disclose-version";
import * as $13 from "svelte/internal/client";
import { onDestroy as onDestroy3 } from "svelte";

// characters/src/runtime.js
var DEFAULT_DB = "https://evil-invaders-default-rtdb.firebaseio.com";
function dbUrl() {
  const base = globalThis.__CHARACTERS_DB__ || DEFAULT_DB;
  return String(base).replace(/\/+$/, "");
}
async function getJson(path, params) {
  const qs = params ? "?" + new URLSearchParams(params) : "";
  const res = await fetch(`${dbUrl()}/${path}.json${qs}`);
  if (!res.ok) throw new Error(`characters db: GET ${path} -> HTTP ${res.status}`);
  return res.json();
}
function fetchCharacter(name) {
  return getJson(`characters/${encodeURIComponent(name)}`);
}
async function listCharacters() {
  const keys = await getJson("characters", { shallow: "true" });
  return keys ? Object.keys(keys).sort() : [];
}
function fetchAtlas(key) {
  return getJson(`atlases/${encodeURIComponent(key)}`);
}
async function saveCharacter(name, data) {
  const res = await fetch(`${dbUrl()}/characters/${encodeURIComponent(name)}.json`, {
    method: "PUT",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(data)
  });
  if (!res.ok) throw new Error(`characters db: PUT characters/${name} -> HTTP ${res.status}`);
  return res.json();
}
async function deleteCharacter(name) {
  const res = await fetch(`${dbUrl()}/characters/${encodeURIComponent(name)}.json`, {
    method: "DELETE"
  });
  if (!res.ok) throw new Error(`characters db: DELETE characters/${name} -> HTTP ${res.status}`);
}
function whenSceneReady(scene) {
  if (scene.sys && scene.sys.displayList) return Promise.resolve(scene);
  return new Promise((resolve) => {
    scene.events.once("start", () => resolve(scene));
  });
}
function loadImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("atlas image failed to decode"));
    img.src = src.startsWith("data:") ? src : `data:image/png;base64,${src}`;
  });
}
function resolveFrame(names, want) {
  if (names.has(want)) return want;
  const swap = want.endsWith(".gif") ? want.slice(0, -4) + ".png" : want.endsWith(".png") ? want.slice(0, -4) + ".gif" : null;
  if (swap && names.has(swap)) return swap;
  const bare = want.replace(/\.(gif|png)$/i, "");
  if (names.has(bare)) return bare;
  for (const ext of [".png", ".gif"]) if (names.has(bare + ext)) return bare + ext;
  return null;
}
function animSets(record) {
  const sets = {};
  const grab = (v) => Array.isArray(v) && v.length && v.every((f) => typeof f === "string") ? v : null;
  if (record && record.anim && typeof record.anim === "object") {
    for (const [k, v] of Object.entries(record.anim)) {
      if (k.startsWith("_")) continue;
      const frames = grab(v);
      if (frames) sets[k] = frames;
    }
  }
  if (!sets.idle) {
    const tex = grab(record && record.texture);
    if (tex) sets.idle = tex;
  }
  return sets;
}
function textureCaches(game) {
  if (!game.__characterCaches) {
    game.__characterCaches = { atlas: /* @__PURE__ */ new Map(), character: /* @__PURE__ */ new Map() };
  }
  return game.__characterCaches;
}
async function ensureAtlasTexture(scene, atlasKey) {
  const textureKey = `char:${atlasKey}`;
  if (scene.textures.exists(textureKey)) return textureKey;
  const caches = textureCaches(scene.game);
  if (!caches.atlas.has(atlasKey)) {
    caches.atlas.set(
      atlasKey,
      (async () => {
        const record = await fetchAtlas(atlasKey);
        if (!record || !record.json || !record.png) {
          throw new Error(`atlas '${atlasKey}' not found in /atlases`);
        }
        const img = await loadImage(record.png);
        const json = typeof record.json === "string" ? JSON.parse(record.json) : record.json;
        if (!scene.textures.exists(textureKey)) {
          scene.textures.addAtlas(textureKey, img, json);
        }
        return textureKey;
      })().catch((e) => {
        caches.atlas.delete(atlasKey);
        throw e;
      })
    );
  }
  return caches.atlas.get(atlasKey);
}
function ensureCharacterAssets(scene, name) {
  const caches = textureCaches(scene.game);
  if (!caches.character.has(name)) {
    caches.character.set(
      name,
      (async () => {
        const data = await fetchCharacter(name);
        if (!data) throw new Error(`character '${name}' not found in /characters`);
        const atlasKey = data.textureKey || name;
        const textureKey = await ensureAtlasTexture(scene, atlasKey);
        const available = new Set(scene.textures.get(textureKey).getFrameNames());
        const sets = animSets(data);
        const animKeys = {};
        let firstFrame = null;
        for (const [setName, wanted] of Object.entries(sets)) {
          const frames = wanted.map((f) => resolveFrame(available, f)).filter(Boolean);
          if (!frames.length) continue;
          if (!firstFrame || setName === "idle") firstFrame = frames[0];
          const key = `char:${name}:${setName}`;
          if (!scene.anims.exists(key)) {
            scene.anims.create({
              key,
              frames: frames.map((frame) => ({ key: textureKey, frame })),
              frameRate: data.frameRate || 8,
              repeat: -1
            });
          }
          animKeys[setName] = key;
        }
        if (!firstFrame) {
          firstFrame = available.values().next().value;
          if (!firstFrame) throw new Error(`character '${name}': atlas '${atlasKey}' has no frames`);
        }
        return { data, textureKey, animKeys, firstFrame };
      })().catch((e) => {
        caches.character.delete(name);
        throw e;
      })
    );
  }
  return caches.character.get(name);
}

// characters/src/Character.svelte
function Character($$anchor, $$props) {
  $13.push($$props, true);
  let x = $13.prop($$props, "x", 3, 0), y = $13.prop($$props, "y", 3, 0), animation = $13.prop($$props, "animation", 3, "idle"), play = $13.prop($$props, "play", 3, true), scale = $13.prop($$props, "scale", 3, void 0), scaleX = $13.prop($$props, "scaleX", 3, void 0), scaleY = $13.prop($$props, "scaleY", 3, void 0), depth = $13.prop($$props, "depth", 3, void 0), alpha = $13.prop($$props, "alpha", 3, void 0), angle = $13.prop($$props, "angle", 3, void 0), flipX = $13.prop($$props, "flipX", 3, false), flipY = $13.prop($$props, "flipY", 3, false), tint = $13.prop($$props, "tint", 3, void 0), visible = $13.prop($$props, "visible", 3, true), originX = $13.prop($$props, "originX", 3, void 0), originY = $13.prop($$props, "originY", 3, void 0), onready = $13.prop($$props, "onready", 3, void 0), onerror = $13.prop($$props, "onerror", 3, void 0);
  const scene = getScene();
  if (!scene) {
    throw new Error(`<${$$props.name || "Character"}> needs a Phaser scene context \u2014 mount it inside <Game><Scene> (5velte-ph4ser) or <Adopt scene={...}>`);
  }
  let sprite = $13.state(null);
  let assets = $13.state(null);
  let destroyed = false;
  whenSceneReady(scene).then(() => ensureCharacterAssets(scene, $$props.name)).then((a) => {
    if (destroyed) return;
    $13.set(assets, $13.proxy(a));
    $13.set(sprite, $13.proxy(scene.add.sprite(x(), y(), a.textureKey, a.firstFrame)));
    onready()?.({
      sprite: $13.get(sprite),
      data: a.data,
      animations: a.animKeys
    });
  }).catch((e) => {
    console.error(`[characters] <${$$props.name}> failed to load:`, e);
    onerror()?.(e);
  });
  $13.user_effect(() => {
    if (!$13.get(sprite)) return;
    $13.get(sprite).x = x();
    $13.get(sprite).y = y();
  });
  $13.user_effect(() => {
    if (!$13.get(sprite)) return;
    if (scale() !== void 0) $13.get(sprite).setScale(scale());
    else if (scaleX() !== void 0 || scaleY() !== void 0) {
      $13.get(sprite).setScale(scaleX() ?? 1, scaleY() ?? 1);
    }
  });
  $13.user_effect(() => {
    if (!$13.get(sprite)) return;
    $13.get(sprite).setFlip(flipX(), flipY());
    $13.get(sprite).setVisible(visible());
    if (depth() !== void 0) $13.get(sprite).setDepth(depth());
    if (alpha() !== void 0) $13.get(sprite).setAlpha(alpha());
    if (angle() !== void 0) $13.get(sprite).setAngle(angle());
    if (tint() !== void 0) $13.get(sprite).setTint(tint());
    else $13.get(sprite).clearTint();
    if (originX() !== void 0 || originY() !== void 0) {
      $13.get(sprite).setOrigin(originX() ?? 0.5, originY() ?? 0.5);
    }
  });
  $13.user_effect(() => {
    if (!$13.get(sprite) || !$13.get(assets)) return;
    const key = $13.get(assets).animKeys[animation()] || $13.get(assets).animKeys.idle;
    if (play() && key) $13.get(sprite).play(key, true);
    else if (!play() && $13.get(sprite).anims) $13.get(sprite).stop();
  });
  onDestroy3(() => {
    destroyed = true;
    $13.get(sprite)?.destroy();
  });
  $13.pop();
}

// characters/src/Adopt.svelte
import "svelte/internal/disclose-version";
import * as $14 from "svelte/internal/client";
import { setContext as setContext4 } from "svelte";
function Adopt($$anchor, $$props) {
  $14.push($$props, true);
  let game = $14.prop($$props, "game", 3, void 0);
  setContext4(GAME_CONTEXT_KEY, game() ?? $$props.scene?.game);
  setContext4(SCENE_CONTEXT_KEY, $$props.scene);
  var fragment = $14.comment();
  var node = $14.first_child(fragment);
  $14.snippet(node, () => $$props.children ?? $14.noop);
  $14.append($$anchor, fragment);
  $14.pop();
}

// characters/src/factory.js
function boundProps(props, name, defaults) {
  return new Proxy(props, {
    get(target, key, receiver) {
      if (key === "name") return name;
      const value = Reflect.get(target, key, receiver);
      return value === void 0 && key in defaults ? defaults[key] : value;
    },
    has(target, key) {
      return key === "name" || key in defaults || Reflect.has(target, key);
    }
  });
}
function character(name, defaults = {}) {
  return ($$anchor, $$props = {}) => Character($$anchor, boundProps($$props, name, defaults));
}

// characters/src/generated.js
var akuma = character("akuma");
var deza1_39 = character("deza1_39");
var deza2_01 = character("deza2_01");
var deza2_02 = character("deza2_02");
var deza2_36 = character("deza2_36");
var deza3_36_konami_chip = character("deza3_36_konami_chip");
var deza3_47 = character("deza3_47");
var deza9_34 = character("deza9_34");
var dezaBoss0 = character("dezaBoss0");
var dezaBoss1 = character("dezaBoss1");
var dezaBoss3 = character("dezaBoss3");
var dukeNukem = character("dukeNukem");
var enemyR = character("enemyR");
var pyramid = character("pyramid");
var red_dress_killer = character("red_dress_killer");
var sakura = character("sakura");
var weirdo = character("weirdo");
var CHARACTERS = [
  "akuma",
  "deza1_39",
  "deza2_01",
  "deza2_02",
  "deza2_36",
  "deza3_36_konami_chip",
  "deza3_47",
  "deza9_34",
  "dezaBoss0",
  "dezaBoss1",
  "dezaBoss3",
  "dukeNukem",
  "enemyR",
  "pyramid",
  "red_dress_killer",
  "sakura",
  "weirdo"
];

// characters/src/index.js
var editorUrl = () => new URL("./editor.js", import.meta.url).href;
async function loadCharacterEditor() {
  const mod = await import(
    /* @vite-ignore */
    editorUrl()
  );
  return mod.default;
}
async function openCharacterEditor(opts = {}) {
  await loadCharacterEditor();
  const overlay = document.createElement("div");
  overlay.style.cssText = "position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:24px;";
  const element = document.createElement("character-editor");
  if (opts.character) element.setAttribute("character", opts.character);
  if (opts.db) element.setAttribute("db", opts.db);
  element.style.cssText = "width:min(1080px,100%);height:min(720px,100%);";
  overlay.appendChild(element);
  const close = () => overlay.remove();
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  element.addEventListener("close", close);
  (opts.target || document.body).appendChild(overlay);
  return { element, close };
}
export {
  Adopt,
  akuma as Akuma,
  ArcadeCollider,
  ArcadePhysics,
  CHARACTERS,
  CONTAINER_CONTEXT_KEY,
  Character,
  Container,
  DEFAULT_DB,
  deza1_39 as Deza139,
  deza2_01 as Deza201,
  deza2_02 as Deza202,
  deza2_36 as Deza236,
  deza3_36_konami_chip as Deza336KonamiChip,
  deza3_47 as Deza347,
  deza9_34 as Deza934,
  dezaBoss0 as DezaBoss0,
  dezaBoss1 as DezaBoss1,
  dezaBoss3 as DezaBoss3,
  dukeNukem as DukeNukem,
  enemyR as EnemyR,
  GAME_CONTEXT_KEY,
  GAME_OBJECT_CONTEXT_KEY,
  Game,
  pyramid as Pyramid,
  Rectangle,
  red_dress_killer as RedDressKiller,
  SCENE_CONTEXT_KEY,
  SPAWNER_CONTEXT_KEY,
  sakura as Sakura,
  Scene,
  Spawner,
  Sprite,
  Text,
  TileSprite,
  weirdo as Weirdo,
  akuma,
  animSets,
  applyArcadeBodyProps,
  applyContainerProps,
  applyGameObjectProps,
  applyRectangleProps,
  applySpriteProps,
  applyTextProps,
  applyTileSpriteProps,
  attachGameObject,
  attachSpriteAnimationEvents,
  bindProp,
  character,
  createGame,
  createScene,
  createSpawner,
  deleteCharacter,
  deza1_39,
  deza2_01,
  deza2_02,
  deza2_36,
  deza3_36_konami_chip,
  deza3_47,
  deza9_34,
  dezaBoss0,
  dezaBoss1,
  dezaBoss3,
  dukeNukem,
  enemyR,
  ensureCharacterAssets,
  fetchAtlas,
  fetchCharacter,
  findGameObjectsByName,
  getContainer,
  getGame,
  getGameObject,
  getScene,
  getSpawner,
  isDestroyed,
  listCharacters,
  loadCharacterEditor,
  onArcadePhysicsEvent,
  onGameEvent,
  onInputEvent,
  onSceneEvent,
  openCharacterEditor,
  pyramid,
  red_dress_killer,
  removeUndefined,
  sakura,
  saveCharacter,
  syncProps,
  toArray,
  useArcadeCollider,
  useArcadePhysics,
  useContainer,
  useGameObject,
  useRectangle,
  useSprite,
  useText,
  useTileSprite,
  weirdo
};
