// GENERATED by characters/build.mjs — one export per /characters entry
// (plus a PascalCase alias, since Svelte templates need capitalized tags).
// Characters added after this build still work via character('<name>').
import { character } from "./factory.js";

export const dukeNukem = character("dukeNukem");
export { dukeNukem as DukeNukem };
export const enemyR = character("enemyR");
export { enemyR as EnemyR };
export const red_dress_killer = character("red_dress_killer");
export { red_dress_killer as RedDressKiller };
export const weirdo = character("weirdo");
export { weirdo as Weirdo };

export const CHARACTERS = [
  "dukeNukem",
  "enemyR",
  "red_dress_killer",
  "weirdo"
];
