// GENERATED by characters/build.mjs — one export per /characters entry
// (plus a PascalCase alias, since Svelte templates need capitalized tags).
// Characters added after this build still work via character('<name>').
import { character } from "./factory.js";

export const akuma = character("akuma");
export { akuma as Akuma };
export const deza1_39 = character("deza1_39");
export { deza1_39 as Deza139 };
export const deza2_01 = character("deza2_01");
export { deza2_01 as Deza201 };
export const deza2_02 = character("deza2_02");
export { deza2_02 as Deza202 };
export const deza2_36 = character("deza2_36");
export { deza2_36 as Deza236 };
export const deza3_36_konami_chip = character("deza3_36_konami_chip");
export { deza3_36_konami_chip as Deza336KonamiChip };
export const deza3_47 = character("deza3_47");
export { deza3_47 as Deza347 };
export const deza9_34 = character("deza9_34");
export { deza9_34 as Deza934 };
export const dezaBoss0 = character("dezaBoss0");
export { dezaBoss0 as DezaBoss0 };
export const dezaBoss1 = character("dezaBoss1");
export { dezaBoss1 as DezaBoss1 };
export const dezaBoss3 = character("dezaBoss3");
export { dezaBoss3 as DezaBoss3 };
export const dukeNukem = character("dukeNukem");
export { dukeNukem as DukeNukem };
export const enemyR = character("enemyR");
export { enemyR as EnemyR };
export const pyramid = character("pyramid");
export { pyramid as Pyramid };
export const red_dress_killer = character("red_dress_killer");
export { red_dress_killer as RedDressKiller };
export const sakura = character("sakura");
export { sakura as Sakura };
export const weirdo = character("weirdo");
export { weirdo as Weirdo };

export const CHARACTERS = [
  "akuma",
  "deza1_39",
  "deza2_01",
  "deza2_02",
  "deza2_36",
  "deza3_36_konami_chip",
  "deza3_47",
  "deza9_34",
  "dezaBoss0",
  "dezaBoss1",
  "dezaBoss3",
  "dukeNukem",
  "enemyR",
  "pyramid",
  "red_dress_killer",
  "sakura",
  "weirdo"
];
